# ADC
GUI_VREF = 1.0
GUI_ADC_RESOLUTION = 12

# Probe config types
GUI_2PROBES = 1
GUI_3PROBES = 2
GUI_4PROBES = 3

GUI_PROBE_1_USED = 1
GUI_PROBE_2_USED = 2
GUI_PROBE_3_USED = 4
GUI_PROBE_4_USED = 8

GUI_PROBE_SUPPLY_DCV = 1
GUI_PROBE_SUPPLY_ACV = 2
GUI_PROBE_SUPPLY_CUR = 3
GUI_PROBE_SUPPLY_GND = 4
GUI_PROBE_MEASURE_VOL = 1
GUI_PROBE_MEASURE_CUR = 2

# Measure config types
GUI_DC_RESISTANCE = 1
GUI_CURRENT_VOLTAGE = 2
GUI_CAPACITANCE_VOLTAGE_2P = 3
GUI_IMPEDANCE_SPECTROSCOPY_2P = 4
GUI_TRANSFER_CHARACTERISTICS = 5
GUI_OUTPUT_CHARACTERISTICS = 6
GUI_CAPACITANCE_VOLTAGE_3P = 7
GUI_ELECTROCHEMICAL = 8
GUI_LOW_RESISTANCE = 9
GUI_PROBE_RESISTANCE = 10
GUI_IMPEDANCE_SPECTROSCOPY_4P = 11