# PCB Constants - ADC
GUI_VREF = 1.0
GUI_ADC_RESOLUTION = 12

# PCB Constants - Probe config types
GUI_2PROBES = 1
GUI_3PROBES = 2
GUI_4PROBES = 3

# PCB Constants - Measure config types
GUI_DC_RESISTANCE = 1
GUI_CURRENT_VOLTAGE = 2
GUI_CAPACITANCE_VOLTAGE_2P = 3
GUI_IMPEDANCE_SPECTROSCOPY_2P = 4
GUI_TRANSFER_CHARACTERISTICS = 5
GUI_OUTPUT_CHARACTERISTICS = 6
GUI_CAPACITANCE_VOLTAGE_3P = 7
GUI_ELECTROCHEMICAL = 8
GUI_LOW_RESISTANCE = 9
GUI_4PROBE_RESISTANCE = 10
GUI_IMPEDANCE_SPECTROSCOPY_4P = 11